---
- hosts: all
  become: yes

  vars:
    docker_edition: 'ce'
    docker_add_repo: true
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
    docker_install_compose_plugin: true

  roles:
    - role: geerlingguy.docker