---
- name: Ensure required roles are installed
  hosts: plex
  tasks:
    - name: Install geerlingguy.docker role
      ansible.builtin.command: ansible-galaxy install geerlingguy.docker

    - name: Run echo command before roles
      command: echo "Hello, Ansible!!!"

- hosts: plex
  become: yes

  vars:
    docker_edition: 'ce'
    docker_add_repo: true
    docker_service_state: started
    docker_service_enabled: true
    docker_restart_handler_state: restarted
    docker_install_compose_plugin: true

  roles:
    - role: geerlingguy.docker

  tasks:
    - name: Run echo command after roles
      command: echo "Hello, Ansible!!!"
