---
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:latest
    command: bash
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible